### ISSUE TITLE
Java 11 support?

### ISSUE THREAD

**Issue by Bhlowe** [fpompermaier/onvif#12]
Did anyone get this to compile and run on newer versions of java? This is more of a generic "how to get javax.xml.soap, jaxb2 to run on java 11.. but hoping someone has a quick pointer.. 

I can add dependencies to get it to compile, but then run errors like:
Error: Unable to initialize main class org.onvif.client.SimpleTest
Caused by: java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file javax/xml/soap/SOAPException

I'll try to answer my own question.. but thought I'd ask... Thanks!

**Comment by fpompermaier** [comment]
Have you tried to look at this? https://www.dariawan.com/tutorials/java/using-jaxb-java-11/

**Comment by Bhlowe** [comment]
That helped! I think I have it.. I'm happy to submit a PR if you want, but it may not be suitable for all users. 

https://github.com/Bhlowe/onvif

My changes adds the javax code to all builds, which is probably not ideal. I think a better solution is to use java profiles to add code... or just add the java 9+ dependencies to the code base that wants to use your code with a java 9+ project.  I will probably experiment with that and comment here.  

Thanks for all your work on this.. I am going to test it a bit more on my webcam rebroadcasting app, siteproxy.. Will try to add value back if I can.. but unfortunately, soap is not my specialty.  

Again.... thanks for your hard work!

**Comment by Bhlowe** [comment]
I'm going to reopen this until it compiles and runs using pure java 12. I think its really close.. Updated https://github.com/Bhlowe/onvif  and it now compiles and builds the stubs (I also added the nice toString() override which makes debugging and printing values better.)

But getting an error running the SimpleTest. Looks like the generated sources for the Services are using an absolute file path.. instead of either setting WSDL_LOCATION to null (previous version) or using a copy from the resource directory. 

    static {
        URL url = null;
        try {
            url = new URL("file:/D:/spring/onvif/onvif-ws-client/src/main/resources/wsdl/media_2.6.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MediaService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/spring/onvif/onvif-ws-client/src/main/resources/wsdl/media_2.6.wsdl");
        }
        WSDL_LOCATION = url;
    }


Any ideas appreciated.

**Comment by Bhlowe** [comment]
Ok. Fixed. Set WSDL_LOCATION to null and that matches he behavior in the previous release. I think I have a version that will build 8-12. Disregard last message. Just want to make sure my fork can be built using jdk 8.

**Comment by fpompermaier** [comment]
Great!

**Comment by fpompermaier** [comment]
Fixed by 42ac69c9d0cf1fdc6e35c77281f859f866572129
