### ISSUE TITLE
Building original project with no change --> failed 

### ISSUE THREAD

**Issue by lsteelandt** [fpompermaier/onvif#18]
Hi,
Thanks for this work, but to contribute, first I need to succeed in building your original version. 
If I do so, Maven fail to build. 
onvif  is SUCCESS 
onvif-ws-client is also SUCCESS
but 
onvif-java FAILED with this error :
` ....blablabla...../onvif-java/src/test/java/org/onvif/client/GetTestDevice.java:[91,19] no suitable constructor found for Scanner(java.io.InputStream,java.nio.charset.Charset)`

I followed instructions on readme.md without changing any list of managed WSDLs. 

my maven --version is :

Apache **Maven 3.6.3**** (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: _<somes folders>_/apache-maven-3.6.3
**Java version: 1.8.0_163**, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/**zulu-8.jdk**/Contents/Home/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.1", arch: "x86_64", family: "mac"

The project still alive ? 

Thanks for any help.

**Comment by fpompermaier** [comment]
Hi,
the project is there to anybody that needs it. If you want to contribute it's ok, now I'll try to understand what's wrong with this...

**Comment by fpompermaier** [comment]
Now the problem should be fixed. Feel free to reopen the issue if the problem persists.
It would be nice,as a first contribution, if you could set up an automatic check builds and PRs, see issue #16.. :wink:
Cheers, Flavio
