### ISSUE TITLE
Information abaut libary

### ISSUE THREAD

**Issue by testniracun** [fpompermaier/onvif#2]
Hi,  
This library supports only client side? Or also server side?

I want to make virtual onvif device (software simulator), which will support profile S.
So I'm wondering if this is possible with this code.

Which developing environment are you using? IDE?

**Comment by fpompermaier** [comment]
Hi,
this library was born to improve the current java (client side) library available at https://github.com/milg0/onvif-java-lib and I use Eclipse as IDE (however this is a maven project so you can use any Java IDE you prefer)..
IMHO the original code cannot be a serious solution (no auto-generated stubs and manually created connection to the server....). I tried to talk to the maintainer but he's be happy with the current solution and he didn't want to change it.

This solution now has auto generated stubs and adopt apache CXF as the base for interfacing with WS.
This has a lot of advantages, such as the possibility to use WS-Notification to interface with the Events (alarms, motion detection, etc) but I still have to be able to write a working example :)
I'm quite near to a solution but I need some more time...if someone is willing to help I'd be very glad to merge PRs..

However I don't think you can use it as a onvif device simulator...I saw that there are some aroud.
Maybe you could contribute with a test class that use a simulator  if you find one that is good :)

**Comment by beegee-tokyo** [comment]
\<QUOTE> (however this is a maven project so you can use any Java IDE you prefer)..\</QUOTE>

I am using Android Studio, but when I want to add this project with '**Project Structure --> Dependencies --> Add Library --> search for onvif**' a search on Maven Central doesn't show any results.
Do I need to add it manually in the build.gradle???

**Comment by fpompermaier** [comment]
Hi,
unfortunately I didn't publish this library on Maven Central and, at the moment, you need to run a mvn install in order to make this libary available in your local repository. If people start asking me for a public release on Maven central I could start thinking at doing it

**Comment by beegee-tokyo** [comment]
Ok, understand.
I am curious if I get your library to work under Android. Will let you know about the results.

**Comment by fpompermaier** [comment]
Great! If you need changes and you want to contribute don't hesitate to create issues or PRs

**Comment by chenycs** [comment]
Hello beegee-tokyo,
Do you integrated to Android Studio?
Could you share how to do that If you did?
Thanks

**Comment by beegee-tokyo** [comment]
@chenycs 
No, I gave up on it. Too many dependencies that are not compiling in Android Studio.

**Comment by chenycs** [comment]
:( 
thank you.

**Comment by fpompermaier** [comment]
Hi to all,
I've just removed the unrelated project from this repository and now everything should be very simple to set up and test (I moved all test classes to test folder). For the moment I close this issue.
Feel free to open new issues to improve this lib or contribute (in particular to interface with event and alarms)
