### ISSUE TITLE
w3.org dropping of HTTP in favour of HTTPS support causes failure

### ISSUE THREAD

**Issue by richard-austin** [fpompermaier/onvif#25]
Hi

I've been using the Onvif library successfully in my CCTV NVR for just over a year. For a couple of days last week, the Onvif discovery was failing. This was due to w3.org testing a planned dropping of support for http requests, which they would send a 301 (or similar) redirect to an https url. The problem is that my cameras use http urls for the schemas and the Onvif library does not redirect by default. Is there a way it can configured to follow redirects?

w3.org are planning to make this change permanent in the near future which would stop Onvif discovery working altogether.

Thanks in advance

**Comment by fpompermaier** [comment]
Just issue a PR to fix this problem and I'll be glad to merge it

**Comment by richard-austin** [comment]
Yes looking into it. When I'm back off hols I'll hopefully get something sorted.

**Comment by richard-austin** [comment]
The calls to w3.org turned out to be caused by the dependencies being incorrect in my project (my project uses gradle rather than maven). Having fixed that, there are no more calls to w3.org and the discovery and device capability checks are faster too. So my bad.
