### ISSUE TITLE
Incorrect datetime string format in SimpleSecurityHandler method getUTCTime()

### ISSUE THREAD

**Issue by msbmteam** [fpompermaier/onvif#36]
Several months ago, I was using this library to connect to an ONVIF camera, but one day the library stopped being able to authenticate with the camera. After some investigation, it turned out that it was due to the date having just rolled over into a new month, causing the number of digits in the day to decrease from 2 to 1 (e.g. April 28, 29, 30 --> May 1, 2, 3)

I was able to fix this issue by changing the day portion of the SimpleDateFormat to have 2 digits instead of 1
("yyyy-MM-**_dd_**'T'HH:mm:ss'Z'" instead of "yyyy-MM-**_d_**'T'HH:mm:ss'Z'")

[Link to the relevant line in SimpleSecurityHandler.java](https://github.com/fpompermaier/onvif/blob/master/onvif-java/src/main/java/de/onvif/soap/SimpleSecurityHandler.java#L146)

See below for a corrected version of this method:
```java
public String getUTCTime() {
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
    sdf.setTimeZone(new SimpleTimeZone(SimpleTimeZone.UTC_TIME, "UTC"));
    Calendar cal = new GregorianCalendar(TimeZone.getTimeZone("UTC"));
    String utcTime = sdf.format(cal.getTime());
    this.utcTime = utcTime;
    return utcTime;
}
```

**Comment by fpompermaier** [comment]
Nice catch! Fixed by fd31ec76bdadf2f1ebfcf1a56c90a3e40d8d4a49
