### ISSUE TITLE
Rebuilding ws stubs

### ISSUE THREAD

**Issue by crearo** [fpompermaier/onvif#6]
I've been trying to find an answer for this [stackoverflow question](https://stackoverflow.com/questions/49937930/wsimport-for-onvif-wsdl-no-service-definition). Since you've worked on building the stubs, could you help me out - I'd preferably like to do it using `wsimport`, without the Apache CXF plugin.

Thanks!

**Comment by fpompermaier** [comment]
I prefer to keep everything inside the pom. Initially I started with wsimport but I faced the problem to deal with WS-Notification for Event ws...
